import { spawnSync } from 'node:child_process';
import { resolve } from 'node:path';

const tests = [
  'test_version_selection.mjs',
  'test_snapshot_summary.mjs',
  'test_delta_safety.mjs',
  'test_snapshot_path_confinement.mjs',
  'test_version_verification.mjs',
  'test_quota_usage.mjs',
  'test_database_retention.mjs',
  'test_temp_cleanup.mjs',
  'test_notification_semantics.mjs',
  'test_dialog_accessibility.mjs',
  'test_pairing_retry_ui.mjs',
  'test_ssd_retention_ui.mjs',
  'test_ssd_path_policy.mjs',
  'test_hyper_manual_setup.mjs',
  'test_hyper_ssh_target.mjs',
  'test_restore_audit.mjs',
  'test_job_health.mjs',
  'test_backup_health_ui.mjs',
  'test_notification_tracker.mjs',
  'test_exclude_policy.mjs',
  'test_safety_settings_ui.mjs',
  'test_format_bytes.mjs',
  'test_icon_labels.mjs',
  'test_auth_config.mjs',
  'test_auth_lifecycle.mjs',
  'test_main_auth.mjs',
  'test_route_authorization.mjs',
  'test_auth_routes.mjs',
  'test_auth_frontend.mjs',
  'test_auth_backup_restore.mjs',
  'test_auth_startup.mjs',
  'test_auth_client_ip.mjs',
  'test_auth_deployment.mjs',
  'test_backup_account_bootstrap.mjs',
  'test_breakglass_runtime_contract.mjs',
  'test_legacy_schema_migration.mjs',
  'test_migration_preflight.mjs',
  'test_fresh_start.mjs',
  'test_database_file_safety.mjs',
  'test_db_backup_policy.mjs',
  'test_peer_auth.mjs',
  'test_peer_secrets.mjs',
  'test_peer_ssh_authorization.mjs',
  'test_root_peer_key_reconciliation.mjs',
  'test_ssh_key_validation.mjs',
  'test_ssh_manager_storage.mjs',
  'test_ssh_connection_policy.mjs',
  'test_run_status.mjs',
  'test_child_process_shutdown.mjs',
  'test_process_shutdown.mjs',
  'test_frontend_run_status.mjs',
  'test_frontend_schedule.mjs',
  'test_peer_run_isolation.mjs',
  'test_run_claim.mjs',
  'test_run_lifecycle.mjs',
  'test_rsync_output.mjs',
  'test_rclone_output.mjs',
  'test_rclone_policy.mjs',
  'test_runtime_config.mjs',
  'test_resource_budget.mjs',
  'test_storage_config.mjs',
  'test_notification_policy_component.mjs',
  'test_media_deletion_policy.mjs',
  'test_media_import_ledger.mjs',
  'test_media_import_status.mjs',
  'test_drive_scanner_completion.mjs',
  'test_eject_policy.mjs',
  'test_immich_command.mjs',
  'test_source_health.mjs',
  'test_forward_auth_trust.mjs',
  'test_peer_url_policy.mjs',
  'test_http_policy.mjs',
  'test_settings_policy.mjs',
  'test_docker_client.mjs',
  'test_docker_api_proxy.mjs',
  'test_schedule_policy.mjs',
  'test_peer_access_policy.mjs',
  'test_pairing_state.mjs',
  'test_pairing_ingress.mjs',
  'test_pairing_http_limits.mjs',
  'test_path_confinement.mjs',
  'test_filesystem_access.mjs',
];

for (const test of tests) {
  const result = spawnSync(process.execPath, [resolve(import.meta.dirname, test)], {
    encoding: 'utf8',
  });
  if (result.stdout) process.stdout.write(result.stdout);
  if (result.stderr) process.stderr.write(result.stderr);
  if (result.status !== 0) process.exit(result.status || 1);
}

console.log(`Mitigation regressions: ${tests.length} files passed`);